# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 600))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:240;height:40;}")
        self.tabWidget.setObjectName("tabWidget")
        self.createVpn = QtWidgets.QWidget()
        self.createVpn.setObjectName("createVpn")
        self.sourceFile = QtWidgets.QWidget(self.createVpn)
        self.sourceFile.setGeometry(QtCore.QRect(10, 10, 541, 101))
        self.sourceFile.setObjectName("sourceFile")
        self.label = QtWidgets.QLabel(self.sourceFile)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.sourceFile)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.sourceFile)
        self.lineEdit.setGeometry(QtCore.QRect(150, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.sourceFile)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 20, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.sourceFile)
        self.pushButton.setGeometry(QtCore.QRect(270, 50, 41, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.sourceFile)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 20, 41, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.sourceFile)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 60, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.createVpn)
        self.tableWidget.setGeometry(QtCore.QRect(40, 180, 541, 341))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("宋体")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label_3 = QtWidgets.QLabel(self.createVpn)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 91, 16))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.createVpn)
        self.widget.setGeometry(QtCore.QRect(630, 10, 291, 511))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 111, 21))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 261, 451))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.createVpn, "")
        self.routeAdjustment = QtWidgets.QWidget()
        self.routeAdjustment.setObjectName("routeAdjustment")
        self.tabWidget.addTab(self.routeAdjustment, "")
        self.linkReplacement = QtWidgets.QWidget()
        self.linkReplacement.setObjectName("linkReplacement")
        self.tabWidget.addTab(self.linkReplacement, "")
        self.ceWithdrawNet = QtWidgets.QWidget()
        self.ceWithdrawNet.setObjectName("ceWithdrawNet")
        self.tabWidget.addTab(self.ceWithdrawNet, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IP承载网脚本自动化生成v1.0"))
        self.label.setText(_translate("MainWindow", "选择调单Excel源文件："))
        self.label_2.setText(_translate("MainWindow", "选择设备全局配置文件："))
        self.pushButton.setText(_translate("MainWindow", "浏览"))
        self.pushButton_2.setText(_translate("MainWindow", "浏览"))
        self.pushButton_3.setText(_translate("MainWindow", "确定"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VPN名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "发布地址段"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PE设备"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PE设备端口"))
        self.label_3.setText(_translate("MainWindow", "调单信息提取："))
        self.label_4.setText(_translate("MainWindow", "生成txt文件如下："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.createVpn), _translate("MainWindow", "新增VPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routeAdjustment), _translate("MainWindow", "路由调整"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linkReplacement), _translate("MainWindow", "链路替换"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ceWithdrawNet), _translate("MainWindow", "CE退网"))

